### ISSUE TITLE
Implement KeyValues1

### ISSUE THREAD

**Issue by yaakov-h** [SteamDatabase/ValveKeyValue#4]
- [X] Parse KV1 text to KV types.
  - [x] Quoted strings
  - [x] Unquoted strings
- [X] Parse KV1 text to object graph.
- [x] Parse KV1 binary to KV types.
- [x] Parse KV1 binary to object graph.
- [x] Handle conditionals:
  - [x] Provide defaults based on current execution environment (`$WIN32`/`$OSX`/`$LINUX`)
  - [X] Allow user to specify conditional variables.
- [x] Handle newlines, tabs and other text escaping.
- [x] Write KV1 types to text.
- [x] Write object graph to text.
- [x] Write KV1 types to binary.
- [ ] Write object graph to binary.
- [x] Handle circular object graphs.
- [ ] Create documentation
- [ ] Create compatibility tests with Valve's KeyValues from tier1 to ensure consistency.
- [x] Parse and write properties
- [ ] Parse and write fields

Stress test: *_english.txt from recent Valve games (Dota 2, CS:GO, TF2).

**Comment by SinZ163** [comment]
* [x] #base support
* [x] #include support

**Comment by xPaw** [comment]
As it turns out KV1 has some type guessing going on: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/tier1/KeyValues.cpp#L2361-L2400

And packed reader passes types into keyvalue, uses `m_iDataType`. When saving to text, it has some type logic as well in there.

**Comment by SinZ163** [comment]
Dota sometimes has duplicate keys, variable length nesting, and types that can be both Collections and Values at the same time.

Duplicate keys come from the fact it uses the key as a type rather than an indexer. (datadriven does this, precache blocks also do this)

Infinite / Variable Length nesting comes from DataDriven items/abilities where you have some keys that are allowed effectively an array of "action"s and some "action" blocks can have keys that are arrays of "actions".

Multi-Type issues are mainly from the "Target" key which can either have a string as a value, or a block of (non-nesting) values.

[Example containing all 3 issues](https://gist.github.com/SinZ163/839b3a1a3c547a5fd03702eb2f572112)

- [x] Duplicate keys
- [ ] Variable Length nesting
- [ ] Multi-Type Strong Serialization

**Comment by xPaw** [comment]
> Provide defaults based on current execution environment ($WIN32/$OSX/$LINUX)

Valve does in `DefaultConditionalSymbolProc` at compile time. (exprevaluator.cpp)

We could provide these, the rest are not available for us (low violence, demo, consoles)
- `WIN32` - appears to be always true if you're not PS3 or X360
- `WINDOWS` - `#ifdef _WIN32 && #ifndef _X360`
- `OSX` - `#elif defined(POSIX) && #elif defined ( OSX ) && #if !defined( LINUX )`
- `LINUX` - `#elif defined(POSIX) && #if defined( LINUX ) && !defined( OSX )`
- `POSIX` - `#elif defined(POSIX)`

I'm just listing these for reference, we can just use .net core helper methods to get the OS.

**Comment by yaakov-h** [comment]
I assume we can ignore PS3 or XBOX outright...

**Comment by xPaw** [comment]
Closing this in favor of having separate issues for each item. Please create issues if there's any missing items.
