### ISSUE TITLE
Implement KeyValues3

### ISSUE THREAD

**Issue by yaakov-h** [SteamDatabase/ValveKeyValue#5]
- [ ] Flagged values
  - [ ] Add Flag to `KVValue` for flagged strings (text) or flagged anything (binary)
  - [ ] Ensure that KV1 serialiser drops the flag when serialising (should happen by default, but check / write unit test)
  - [ ] Ensure that flag and value is maintained when deserialising to a strongly-typed object model that has a `KVValue` field/property.
- [ ] Create the rest of this checklist :clipboard:

**Comment by xPaw** [comment]
KV3 text is implemented here, and I think it has no known issues: https://github.com/SteamDatabase/ValveResourceFormat/tree/master/ValveResourceFormat/Serialization/KeyValues

KV3 binary: https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/Resource/ResourceTypes/BinaryKV3.cs

Binary is slightly complicated due to multiple compressions and versions, but luckily all of that has been figured out by now.

The only issue there is the `ConvertBinaryOnlyKVType` function because binary kv3 has some special types (like bytes for true/false booleans and uint32 in binary which maps to uint64 in the text one).
